<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17045" started-at="2019-12-12T22:54:57Z" finished-at="2019-12-12T22:55:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17045" started-at="2019-12-12T22:54:57Z" finished-at="2019-12-12T22:55:14Z">
      <class name="ups.pack.testRunner.UpsLoginTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ups.pack.testRunner.UpsLoginTest@7a35b0f5]" name="beforeMethod" is-config="true" duration-ms="5947" started-at="2019-12-12T22:54:57Z" finished-at="2019-12-12T22:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ups.pack.testRunner.UpsShipingTest@5e2c3d18]" name="beforeMethod" is-config="true" duration-ms="6531" started-at="2019-12-12T22:55:03Z" finished-at="2019-12-12T22:55:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:ups.pack.testRunner.UpsLoginTest@7a35b0f5]" name="loginTest" duration-ms="1859" started-at="2019-12-12T22:55:09Z" finished-at="2019-12-12T22:55:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at ups.pack.testRunner.UpsLoginTest.loginTest(UpsLoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:ups.pack.testRunner.UpsLoginTest@7a35b0f5]" name="afterTest" is-config="true" duration-ms="142" started-at="2019-12-12T22:55:13Z" finished-at="2019-12-12T22:55:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:ups.pack.testRunner.UpsShipingTest@5e2c3d18]" name="afterTest" is-config="true" duration-ms="223" started-at="2019-12-12T22:55:14Z" finished-at="2019-12-12T22:55:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- ups.pack.testRunner.UpsLoginTest -->
      <class name="ups.pack.testRunner.UpsShipingTest">
        <test-method status="PASS" signature="shippingTest()[pri:0, instance:ups.pack.testRunner.UpsShipingTest@5e2c3d18]" name="shippingTest" duration-ms="2324" started-at="2019-12-12T22:55:11Z" finished-at="2019-12-12T22:55:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shippingTest -->
      </class> <!-- ups.pack.testRunner.UpsShipingTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
